# Generated by Django 3.0.1 on 2020-01-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.CharField(default='', editable=False, max_length=40)),
                ('Title', models.CharField(max_length=40)),
                ('Inventors', models.CharField(max_length=80)),
                ('Applicants', models.CharField(max_length=40)),
                ('IPC', models.CharField(max_length=480)),
                ('CPC', models.CharField(max_length=480)),
                ('Country', models.CharField(default='', editable=False, max_length=50)),
                ('Publication_number', models.CharField(default='', editable=False, max_length=40)),
                ('Publication_Year', models.CharField(default='', editable=False, max_length=40)),
                ('Earliest_publication', models.CharField(default='', editable=False, max_length=40)),
                ('Family_number', models.CharField(default='', editable=False, max_length=80)),
                ('Earliest_priority', models.CharField(default='', editable=False, max_length=80)),
            ],
        ),
    ]
