# Generated by Django 3.0.1 on 2020-01-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Publication_date',
            field=models.CharField(default='', editable=False, max_length=80),
        ),
    ]
