# Generated by Django 3.0.1 on 2020-01-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_report_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Family_number',
            field=models.IntegerField(),
        ),
    ]
