# Generated by Django 3.0.1 on 2020-01-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200116_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Family_number',
            field=models.CharField(default='', editable=False, max_length=80),
        ),
    ]
