# Generated by Django 3.0.1 on 2020-01-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200116_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='CPC',
            field=models.CharField(max_length=4880),
        ),
    ]
