# Generated by Django 3.0.1 on 2020-01-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200116_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='CPC',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='IPC',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='No',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='Publication_number',
            field=models.IntegerField(),
        ),
    ]
