# Generated by Django 3.0.1 on 2020-01-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200116_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='CPC',
            field=models.CharField(default='', editable=False, max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='Family_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='IPC',
            field=models.CharField(default='', editable=False, max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='Publication_number',
            field=models.CharField(default='', editable=False, max_length=400),
        ),
    ]
