# Generated by Django 3.0.1 on 2020-01-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200116_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='CPC',
            field=models.CharField(max_length=4880),
        ),
        migrations.AlterField(
            model_name='report',
            name='Family_number',
            field=models.CharField(default='', editable=False, max_length=800),
        ),
        migrations.AlterField(
            model_name='report',
            name='IPC',
            field=models.CharField(max_length=480),
        ),
        migrations.AlterField(
            model_name='report',
            name='No',
            field=models.CharField(default='', editable=False, max_length=40),
        ),
    ]
