# Generated by Django 3.0.1 on 2020-01-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20200116_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Applicants',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='CPC',
            field=models.CharField(max_length=4880, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Country',
            field=models.CharField(default='', editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Earliest_publication',
            field=models.CharField(default='', editable=False, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Family_number',
            field=models.CharField(default='', editable=False, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='IPC',
            field=models.CharField(max_length=480, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Inventors',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='No',
            field=models.CharField(default='', editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Publication_Year',
            field=models.CharField(default='', editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Publication_date',
            field=models.CharField(default='', editable=False, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Publication_number',
            field=models.CharField(default='', editable=False, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Title',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
