# Generated by Django 3.0.1 on 2020-01-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20200116_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Publication_date',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
