# Generated by Django 3.0.1 on 2020-01-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20200122_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Publication_date',
            field=models.DateField(null=True),
        ),
    ]
