# Generated by Django 3.0.1 on 2020-01-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20200122_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Publication_date',
            field=models.CharField(default='', editable=False, max_length=40, null=True),
        ),
    ]
